/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.ConexaoDAO;
import DAO.ProdDAO;
import DTO.ProdDTO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.DefaultComboBoxModel;

import javax.swing.JOptionPane;
/**
 *
 * @author danil
 */
public class ProdTela extends javax.swing.JFrame {

    /**
     * Creates new form ProdTela
     */
    public ProdTela() {
        super ("Produtos");
        initComponents();
        buscarProdutos();
        setLocationRelativeTo(null);
    }

    private void buscarProdutos() {
        try {
            ProdDAO dao = new ProdDAO();
            ProdDTO[] produtos = dao.obterProduto();
            produtosComboBox.setModel(new DefaultComboBoxModel<>(produtos));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Produto não encontrado, tente novamente mais tarde.");
            e.printStackTrace();
        }
    }
    
    private void adicionarProduto() {
        Connection conn;
        PreparedStatement pstm;
        String sql = "INSERT INTO prod (nome_prod, unidadeMed_prod, valor_prod) VALUES (?, ?, ?)";
        conn = new ConexaoDAO().conectaBD();
        try {
            
            pstm = conn.prepareStatement(sql);
            pstm.setString(1, nomeProdTextField.getText());
            pstm.setString(2, unidadeProdTextField.getText());
            pstm.setDouble(3, Double.parseDouble(precoProdTextField.getText()));
            
            pstm.execute();
            pstm.close();
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "produtoDAO" + e);
        }
    }
    
    private void removerProduto() {
        Connection conn;
        PreparedStatement pstm;
        String sql = "DELETE FROM prod WHERE id_prod = ?";
        conn = new ConexaoDAO().conectaBD();
        try {
            
            pstm = conn.prepareStatement(sql);
            pstm.setInt(1, Integer.parseInt(idProdTextField.getText()));
            
            pstm.execute();
            pstm.close();
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "produtoDAO" + e);
        }
    }
    
    private void atualizarProduto() {
        Connection conn;
        PreparedStatement pstm;
        String sqlNome = "UPDATE prod SET nome_prod = ? WHERE id_prod = ?";
        String sqlUnidade = "UPDATE prod SET unidadeMed_prod = ? WHERE id_prod = ?";
        String sqlPreco = "UPDATE prod SET valor_prod = ? WHERE id_prod = ?";
        conn = new ConexaoDAO().conectaBD();
        if (nomeProdTextField.getText() != "") {
            try {
                pstm = conn.prepareStatement(sqlNome);
                pstm.setString(1, nomeProdTextField.getText());
                pstm.setInt(2, Integer.parseInt(idProdTextField.getText()));
                pstm.execute();
                pstm.close();
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "produtoDAO" + e);
            }
        }
        if (unidadeProdTextField.getText() != "") {
            try {   
                pstm = conn.prepareStatement(sqlUnidade);
                pstm.setString(1, unidadeProdTextField.getText());
                pstm.setInt(2, Integer.parseInt(idProdTextField.getText()));
                pstm.execute();
                pstm.close();
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "produtoDAO" + e);
            }
        }
        if (precoProdTextField.getText() != "") {
            try {
                pstm = conn.prepareStatement(sqlPreco);
                pstm.setDouble(1, Double.parseDouble(precoProdTextField.getText()));
                pstm.setInt(2, Integer.parseInt(idProdTextField.getText()));
                pstm.execute();
                pstm.close();
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "produtoDAO" + e);
            }
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        produtosComboBox = new javax.swing.JComboBox<>();
        idProdTextField = new javax.swing.JTextField();
        nomeProdTextField = new javax.swing.JTextField();
        unidadeProdTextField = new javax.swing.JTextField();
        precoProdTextField = new javax.swing.JTextField();
        novoProdButton = new javax.swing.JButton();
        atualizarProdButton = new javax.swing.JButton();
        removerProdButton = new javax.swing.JButton();
        cancelarProdButton = new javax.swing.JButton();
        voltarProdButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gerenciar Produtos"));

        produtosComboBox.setMaximumRowCount(50);

        idProdTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Id"));
        idProdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idProdTextFieldActionPerformed(evt);
            }
        });

        nomeProdTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        nomeProdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeProdTextFieldActionPerformed(evt);
            }
        });

        unidadeProdTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Unidade"));
        unidadeProdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadeProdTextFieldActionPerformed(evt);
            }
        });

        precoProdTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Preço"));
        precoProdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoProdTextFieldActionPerformed(evt);
            }
        });

        novoProdButton.setText("Novo");
        novoProdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoProdButtonActionPerformed(evt);
            }
        });

        atualizarProdButton.setText("Atualizar");
        atualizarProdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarProdButtonActionPerformed(evt);
            }
        });

        removerProdButton.setText("Remover");
        removerProdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerProdButtonActionPerformed(evt);
            }
        });

        cancelarProdButton.setText("Cancelar");
        cancelarProdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarProdButtonActionPerformed(evt);
            }
        });

        voltarProdButton.setText("Voltar");
        voltarProdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarProdButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(produtosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(unidadeProdTextField)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(idProdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nomeProdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(precoProdTextField)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(novoProdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removerProdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(voltarProdButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(atualizarProdButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(cancelarProdButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(produtosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idProdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeProdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precoProdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unidadeProdTextField))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novoProdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atualizarProdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removerProdButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(cancelarProdButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(voltarProdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeProdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeProdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeProdTextFieldActionPerformed

    private void unidadeProdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadeProdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadeProdTextFieldActionPerformed

    private void voltarProdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarProdButtonActionPerformed
                    DashboardAdminTela vs = new DashboardAdminTela();
                    vs.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_voltarProdButtonActionPerformed

    private void idProdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idProdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idProdTextFieldActionPerformed

    private void novoProdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoProdButtonActionPerformed
        adicionarProduto();
        buscarProdutos();
        nomeProdTextField.setText("");
        unidadeProdTextField.setText("");
        precoProdTextField.setText("");
    }//GEN-LAST:event_novoProdButtonActionPerformed

    private void removerProdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerProdButtonActionPerformed
        removerProduto();   
        buscarProdutos();
        idProdTextField.setText("");
    }//GEN-LAST:event_removerProdButtonActionPerformed

    private void atualizarProdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarProdButtonActionPerformed
        atualizarProduto();
        buscarProdutos();
        nomeProdTextField.setText("");
        unidadeProdTextField.setText("");
        precoProdTextField.setText("");
        idProdTextField.setText("");
    }//GEN-LAST:event_atualizarProdButtonActionPerformed

    private void cancelarProdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarProdButtonActionPerformed
        nomeProdTextField.setText("");
        unidadeProdTextField.setText("");
        precoProdTextField.setText("");
        idProdTextField.setText("");
    }//GEN-LAST:event_cancelarProdButtonActionPerformed

    private void precoProdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoProdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precoProdTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarProdButton;
    private javax.swing.JButton cancelarProdButton;
    private javax.swing.JTextField idProdTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeProdTextField;
    private javax.swing.JButton novoProdButton;
    private javax.swing.JTextField precoProdTextField;
    private javax.swing.JComboBox<ProdDTO> produtosComboBox;
    private javax.swing.JButton removerProdButton;
    private javax.swing.JTextField unidadeProdTextField;
    private javax.swing.JButton voltarProdButton;
    // End of variables declaration//GEN-END:variables
}
