/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import javax.swing.JOptionPane;

/**
 *
 * @author ronil
 */
public class TelaBebidas extends javax.swing.JFrame {

    /**
     * Creates new form TelaBebidas
     */
    public TelaBebidas() {
        initComponents();
         getContentPane().setBackground(new java.awt.Color(255,145,77));
    }
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnVoltar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnCancelarPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(255, 255, 253));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Refrigerantecerto.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createTitledBorder("Refrigerante"));
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 130, 258, 173));

        jButton3.setBackground(new java.awt.Color(255, 255, 253));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cafe3certo.png"))); // NOI18N
        jButton3.setBorder(javax.swing.BorderFactory.createTitledBorder("Café"));
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 423, 227, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 253));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sucocerto.png"))); // NOI18N
        jButton4.setBorder(javax.swing.BorderFactory.createTitledBorder("Sucos"));
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 423, 260, 195));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cerveja3.png"))); // NOI18N
        jButton5.setBorder(javax.swing.BorderFactory.createTitledBorder("Cerveja"));
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(862, 130, 190, 175));

        jButton6.setBackground(new java.awt.Color(255, 255, 253));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/drinks1.png"))); // NOI18N
        jButton6.setBorder(javax.swing.BorderFactory.createTitledBorder("Drinks"));
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(862, 425, -1, 193));

        jButton1.setBackground(new java.awt.Color(255, 255, 253));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Agua-mineral-certa1.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createTitledBorder("Água"));
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 130, 227, -1));

        btnVoltar1.setBackground(new java.awt.Color(255, 255, 253));
        btnVoltar1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnVoltar1.setText("Voltar");
        btnVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 32, 128, 49));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 21)); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 666, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 21)); // NOI18N
        jLabel2.setText("Cappuccino:    R$7,50");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 666, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 21)); // NOI18N
        jLabel3.setText("Drinks:  R$15,90");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(862, 636, 177, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 21)); // NOI18N
        jLabel4.setText("Refrigerante 1,5L:   R$6,80");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 357, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 21)); // NOI18N
        jLabel5.setText("Suco:  R$6,00");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 630, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 21)); // NOI18N
        jLabel6.setText("Refrigerante 300ml:   R$3,00");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 321, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 21)); // NOI18N
        jLabel7.setText("Café:   R$4,00");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 634, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 21)); // NOI18N
        jLabel8.setText("Água Mineral:   R$2,00");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 321, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 21)); // NOI18N
        jLabel9.setText("Água com Gás:  R$3,50");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 357, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 21)); // NOI18N
        jLabel10.setText("Cerveja 1L:   R$6,80");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(862, 359, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 21)); // NOI18N
        jLabel11.setText("Cerveja 300ml:  R$3,50");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(862, 323, -1, -1));

        jLabel12.setFont(new java.awt.Font("Curlz MT", 0, 60)); // NOI18N
        jLabel12.setText("Bebidas");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 21, -1, -1));

        btnCancelarPedido.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelarPedido.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnCancelarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarPedido.setText("Cancelar Pedido");
        btnCancelarPedido.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 696, 150, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void voltar(){
         
        PedidosGeraisToten vs = new PedidosGeraisToten();
         vs.setVisible(true); 
  
    }
    
    private void btnVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar1ActionPerformed
        voltar();
        this.dispose();
    }//GEN-LAST:event_btnVoltar1ActionPerformed

    private void btnCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPedidoActionPerformed
        int resultado =JOptionPane.showConfirmDialog(null, "Deseja Mesmo cancelar?", "Cancelando Pedido ...",JOptionPane.YES_NO_OPTION,  JOptionPane.INFORMATION_MESSAGE);

        if (resultado == JOptionPane.YES_OPTION){
            InicialToten vss = new InicialToten();
            vss.setVisible(true);
            this.dispose();
        }
    
    }//GEN-LAST:event_btnCancelarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBebidas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarPedido;
    private javax.swing.JButton btnVoltar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
