package VIEW;

import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Alana
 */
public class TelaLanches extends javax.swing.JFrame {

    /**
     * Creates new form Lanches
     */
    public TelaLanches() {
        setTitle("LANCHES");
        initComponents();
     getContentPane().setBackground(new java.awt.Color(255,145,77));

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        btnCancelarPedido = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtnMisto = new javax.swing.JButton();
        BtnNatural = new javax.swing.JButton();
        BtnMortadela = new javax.swing.JButton();
        BtnTorta = new javax.swing.JButton();
        BtnCoxinha = new javax.swing.JButton();
        BtnBeirute = new javax.swing.JButton();
        BtnHamburguer = new javax.swing.JButton();
        BtnBauru = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lanches");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVoltar.setBackground(new java.awt.Color(255, 255, 248));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 117, 47));

        btnCancelarPedido.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelarPedido.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnCancelarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarPedido.setText("Cancelar Pedido");
        btnCancelarPedido.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 158, 30));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 52)); // NOI18N
        jLabel2.setText("Lanches e Salgados");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        BtnMisto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MistoQuente2.jpg"))); // NOI18N
        BtnMisto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Misto quente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        getContentPane().add(BtnMisto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        BtnNatural.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sanduiche natural2.jpg"))); // NOI18N
        BtnNatural.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sanduíche Natural", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        getContentPane().add(BtnNatural, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        BtnMortadela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sanduicheMortadela2.jpg"))); // NOI18N
        BtnMortadela.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sanduíche mortadela", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        getContentPane().add(BtnMortadela, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, -1, -1));

        BtnTorta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/TortaSalgada.jpg"))); // NOI18N
        BtnTorta.setToolTipText("");
        BtnTorta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Torta Salgada", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        getContentPane().add(BtnTorta, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, -1, -1));

        BtnCoxinha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/coxinha2.jpg"))); // NOI18N
        BtnCoxinha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Coxinha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        getContentPane().add(BtnCoxinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        BtnBeirute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/beirute2.jpg"))); // NOI18N
        BtnBeirute.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Beirute", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        getContentPane().add(BtnBeirute, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));

        BtnHamburguer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Hamburguer2.jpg"))); // NOI18N
        BtnHamburguer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hamburguer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        getContentPane().add(BtnHamburguer, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        BtnBauru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/joelho.jpg"))); // NOI18N
        BtnBauru.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bauru", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        getContentPane().add(BtnBauru, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 30)); // NOI18N
        jLabel1.setText("R$: 3,50");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 336, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 336, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 30)); // NOI18N
        jLabel5.setText("R$: 21,00");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 30)); // NOI18N
        jLabel6.setText("R$: 3,00");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, -1, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 342, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 30)); // NOI18N
        jLabel8.setText("R$: 25,00");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, -1, -1));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(896, 336, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 30)); // NOI18N
        jLabel10.setText("R$:3,00");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 30)); // NOI18N
        jLabel11.setText("R$: 3,50");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 30)); // NOI18N
        jLabel12.setText("R$: 4,40");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 540, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 30)); // NOI18N
        jLabel13.setText("R$: 05,00");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void voltar(){
         
        PedidosGeraisToten vs = new PedidosGeraisToten();
         vs.setVisible(true); 
  
    }
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed

         voltar();
         this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPedidoActionPerformed
        int resultado =JOptionPane.showConfirmDialog(null, "Deseja Mesmo cancelar?", "Cancelando Pedido ...",JOptionPane.YES_NO_OPTION,  JOptionPane.INFORMATION_MESSAGE);
        
        if (resultado == JOptionPane.YES_OPTION){
        InicialToten vss = new InicialToten(); 
        vss.setVisible(true);
        this.dispose();
   
    }//GEN-LAST:event_btnCancelarPedidoActionPerformed
    }
    
          /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLanches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLanches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLanches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLanches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLanches().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBauru;
    private javax.swing.JButton BtnBeirute;
    private javax.swing.JButton BtnCoxinha;
    private javax.swing.JButton BtnHamburguer;
    private javax.swing.JButton BtnMisto;
    private javax.swing.JButton BtnMortadela;
    private javax.swing.JButton BtnNatural;
    private javax.swing.JButton BtnTorta;
    private javax.swing.JButton btnCancelarPedido;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    
}
